### ISSUE TITLE
Deals should have a 'quorum' field.

### ISSUE THREAD

**Issue by andela-uawili** [andela/troupon#69]
The quorum field represents the minimum number of users that must by buy the deal before it can actually be redeemed. Similar to the way it works on Groupon

**Comment by andela-cnnadi** [comment]
What's the update on this issue?

**Comment by andela-aomondi** [comment]
I see this feature has been implemented. We should close this issue.

**Comment by andela-jmwangi** [comment]
Closing this issue as it is already implemented.
